### ISSUE TITLE
配列的入力に対応

### ISSUE THREAD

**Issue by hakatashi** [tsg-ut/mnemo#102]
https://github.com/tsg-ut/mnemo/issues/101#issuecomment-254102967

**Comment by moratorium08** [comment]
配列でかい時、表示どうするべきですか

**Comment by hakatashi** [comment]
悩ましい⋯⋯現状の枠内で頑張るなら入力値の欄の内部をスクロールできるようにする、とかかな⋯⋯。もしくは左側のパネル全体をスクロール可能にするとか。

全体的に設計を見直さないといけなさそう。

**Comment by moratorium08** [comment]
一定文字数以上は"50,[1,2,3,4,5..."みたいにしてしまってもいいかなと思うんですが

**Comment by hakatashi** [comment]
応急処置としてはそれでよさそう

**Comment by moratorium08** [comment]
![2016-10-30 21 32 49](https://cloud.githubusercontent.com/assets/4726469/19836583/7a797ea0-9ee8-11e6-9d9c-12f9e77ad16a.png)
こんな感じでいいですか？

**Comment by hakatashi** [comment]
:+1:

**Comment by moratorium08** [comment]
プルリク確認お願いします

**Comment by moratorium08** [comment]
あ、５秒くらい待ってください

**Comment by moratorium08** [comment]
プルリク確認お願いします
