### ISSUE TITLE
functional testが通らない

### ISSUE THREAD

**Issue by cookie-s** [tsg-ut/mnemo#114]
え、人々通ってますか？
例えば
`mocha "test/functional/index.ls" --reporter spec --compilers ls:livescript`
とかすると、

```
Application
    1) "before all" hook


  0 passing (10s)
  1 failing

  1) Application "before all" hook:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
```

とか言われます。nightmareのバージョン上げたから？

**Comment by hakatashi** [comment]
うーん、 @satos---jp からも前同じようなこと言われたんですよね⋯⋯。

index.lsの `show: false` を `show: true` に書き換えてどういう風に表示されるか教えてもらえますか?

**Comment by hakatashi** [comment]
あと同じindex.lsの `@timeout 10000` をもっと大きな値 (`@timeout 600000` で1分) に変えてみたり

**Comment by cookie-s** [comment]
`show: true`、`@timeout 600000` 、どちらもだめです。
後者の変更では、当たり前ですが一分戻ってこなくなります。
一応エラーに言われたとおり.doneをつけたら治ります。

ぐぐったら、nightmareのversion `^2.8.1`は、`2.x.x`にマッチするらしいので、人々はアップデートされていないのでは？（そしてcompatibleでない版を出したのにmajor versionを上げない人々が悪い？）

**Comment by cookie-s** [comment]
当方、いまさっきgit cloneしてnpm installしたことも追記しておきます

**Comment by hakatashi** [comment]
`^2.8.1`は2.8.1以上3.0.0未満にしかマッチしないのです⋯⋯
https://semver.npmjs.com/

前者の変更、新しいウィンドウが表示されたりもしないですか? 謎だなあ⋯⋯。

**Comment by cookie-s** [comment]
さっき書いたの、間違っていた。
^2.8.1は2.8.1以上3.0.0未満だった。

**Comment by cookie-s** [comment]
X Window Systemを入れてない、CUIのLinuxです。ウィンドウなんてなかった。

**Comment by hakatashi** [comment]
あっ、それはだめですね。ウィンドウシステムが必要なので↓とか見てxvfdを入れてみてください。
https://github.com/electron/electron/blob/master/docs/tutorial/testing-on-headless-ci.md

**Comment by cookie-s** [comment]
もしかしてchromiumも要りますか？（だとしたら開発断念する...）

**Comment by hakatashi** [comment]
chromiumはelectronに含まれているので手動で入れる必要はないはず⋯⋯

**Comment by cookie-s** [comment]
electronは別途入れる必要があるということですか

**Comment by hakatashi** [comment]
electronも `npm install` したときにnightmare経由で入るので入れる必要はないです。

`npm ls electron-prebuilt` と実行してみて `electron-prebuilt@1.3.8` とか表示されれば手元に入ってます。

**Comment by cookie-s** [comment]
uhm...
Xvfb入れて動かして、DISPLAYも設定しましたが、なんで動かないんだろう...

**Comment by hakatashi** [comment]
`xvfb-run npm test` とか `xvfb-run npm run functional` とかしても同じですか?

**Comment by cookie-s** [comment]
変わらず。

**Comment by hakatashi** [comment]
再現したかも。 index.lsの `center: true` のあとに `wait-timeout: 1000` を挿入するとどうなりますか? @cookie-s

**Comment by cookie-s** [comment]
解決しました。
まず、npm installとXvfbのinstallだけではだめでした。

http://qiita.com/imunew/items/f1cf5e2553fc77df28ed#%E5%AE%9F%E8%A1%8C%E6%99%82%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3 を参考に、DEBUG=electron:*とかしたら、全然ライブラリが足りて無いことがデバッグ情報として示されて、結局(ArchLinuxの)package electronを入れたら動き始めました。

ただ、mocha-loggerで表示されるlaunch timeが5000ms～で、
各functional testの@nightmare.refresh!waitにも3000ms～かかってしまって、(refreshの方の)timeoutにひっかかってしまいました。
まあたぶんこれは僕のPCというか仮想マシンが貧弱なせいなので仕方がないですよね。

**Comment by cookie-s** [comment]
たぶんpackageとして必要なのはhttps://github.com/segmentio/nightmare/issues/224#issuecomment-141575361 のあたりに書いてあって、僕はelectronというpackageを入れたらdependenciesとして全部入ったということです。

**Comment by cookie-s** [comment]
今よく読み返したら、https://github.com/tsg-ut/mnemo/issues/114#issuecomment-256425239 の、electron-prebuilt入ってなかった...(electronは入ってた)
