### ISSUE TITLE
Firefoxでステージの表示がおかしい

### ISSUE THREAD

**Issue by hakatashi** [tsg-ut/mnemo#121]
なにこれ

![2016-10-28 10_02_08-mnemo](https://cloud.githubusercontent.com/assets/3126484/19790745/c1398a5a-9cf5-11e6-8e3b-a3b5d339ae27.png)
# 環境

Firefox 49.0.1 / Windows 10
# 再現手順
1. http://sig.tsg.ne.jp/mnemo/ を開く
2. 「ステージセレクト」をクリック
3. 「6乗」をクリック
4. モーダルを閉じる

**Comment by cookie-s** [comment]
何が問題かといえば、Firefoxではパネルにスクロールバーがついてないことですね。
そのせいでパネル.panel-areaが縦に長くなってしまい、左側の.pipe-areaもそれに引きづられて長くなり、
flexboxによってあちこちがそれ基準に伸びる、という感じですね。

デザイン面を除いても、Firefoxではパネルの隠れているところ（この6乗問題だと掛け算）が事実上選択できないという致命的なバグがあります。
6乗問題で掛け算禁止とか本当に致命的では。

**Comment by cookie-s** [comment]
あんまり根本ではなさそう
