### ISSUE TITLE
作業画面を拡大する機能を追加する

### ISSUE THREAD

**Issue by gasin** [tsg-ut/mnemo#124]
作業画面が環境や画面サイズによってはかなり小さくなるので画面いっぱいにする機能があると嬉しいです

**Comment by hakatashi** [comment]
#84 と同じかな? CSSを全面的に書き換えて小さい画面ではスクロールするようにしたいなーと思ってる。

**Comment by gasin** [comment]
IO表はいいのですがこのように作業画面が小さすぎるので拡大できるような機能が欲しいです(jpgファイルにしたらもはや線が見えなくなってしまいました）
![mmnemo](https://cloud.githubusercontent.com/assets/7404299/19797108/d0c5a35e-9d23-11e6-9279-73b378c5f6fa.jpg)

**Comment by hakatashi** [comment]
小画面対応で解決できそうなので #84 に統合します。
