### ISSUE TITLE
powブロックの演算結果を-∞方向に丸める

### ISSUE THREAD

**Issue by gasin** [tsg-ut/mnemo#127]
割り算のときとかに少数で結果が出ますが、整数値のほうが良い気がします（int型のノリで）

**Comment by hakatashi** [comment]
割り算の結果は既に整数のはず。残りだとpowブロックが整数で閉じてないので結果を切り捨てにしたいと思っている。

**Comment by gasin** [comment]
あ、そうですね、powです

**Comment by hakatashi** [comment]
Fixed by #128.
