### ISSUE TITLE
emptyをpanelに含める

### ISSUE THREAD

**Issue by cookie-s** [tsg-ut/mnemo#139]
emptyをそもそも、panelに無限個含めることにすれば、
takeAndPlaceその他でemptyかどうかのつらい場合分けしなくて済んでコーディング側もうれしいし、
ミスって配置してしまったblockを消すことが可能になってユーザ側もうれしいしで、
わりとwin-winだと思うんだけどどう？

特に #136 で明確に使用ブロック数がステータスとされようとしている今、
これじゃないにせよblockを消す手立ては必要だよなぁ。
（このissueが実現するときは、使用ブロック数のcountの際はemptyを特別扱いしなければならないだろうが。)

（多分否定的な意見もある気はする）

**Comment by cookie-s** [comment]
あ、右クリックで消えるんだっけ。

**Comment by hakatashi** [comment]
右クリックで消せるけど、スマホ対応のことを考えるとemptyをpanelに含めるのはありかなーとは思ってる。

でもまあ、それなら他にもっといい方法ありそうだし、スマホ対応するまで様子見でいい気がする。
