### ISSUE TITLE
仕様に関して

### ISSUE THREAD

**Issue by moratorium08** [tsg-ut/mnemo#14]
問題作ったときにいくつか思ったことの羅列です

1. 割り算、小数になるととても使いづらいので仕様としてC言語の/と同じ感じでfloorとった方が問題にしやすい
2. これ解消しようとしても難しいですが、ループ物とかは、平面グラフ的制約をどう乗り越えるか問題みたいになってしまう。
3. ビット演算と不等号演算子を導入したい。

**Comment by hakatashi** [comment]
1. よさそう
2. 交差する十字ワイヤーを導入するとかが必要かなー
3. よさそう(ビット演算はゲーム的に難しそうだけどあっていいと思う)

**Comment by hakatashi** [comment]
done
