### ISSUE TITLE
分岐点(ポイント)ブロックを実装

### ISSUE THREAD

**Issue by hakatashi** [tsg-ut/mnemo#141]
ポイントブロックの画像を作ったので、実装する。

![](https://github.com/tsg-ut/mnemo/raw/master/image/switch1.png) ![](https://github.com/tsg-ut/mnemo/raw/master/image/switch2.png) ![](https://github.com/tsg-ut/mnemo/raw/master/image/switch3.png)

挙動として、例えば一番左のブロックは、

* 左から来たDataは右に送る
* 上から来たDataは右に送る
* 右から来たDataは上と左に送る

という感じ。回転もできるようにする。

Dataが画像の線上に沿って動くようにする必要はない。

画像はswitchという名前にしたが、ON/OFFするやつのスイッチと紛らわしいので、pointに改名したほうがいいかもしれない。

テストも書いてほしい。

**Comment by hakatashi** [comment]
回転操作の他に反転操作もできるようにした方がいいかな⋯⋯。

**Comment by akouryy** [comment]
私がやっていいですか？

**Comment by hakatashi** [comment]
まかせた！

**Comment by akouryy** [comment]
名前は被りの少なそうなjunctionを推したいです
block-configsのtypeに命名規則はありますか？

**Comment by hakatashi** [comment]
junctionよさそう。typeは適当でよいです(今回の場合typeもjunctionかな)

**Comment by akouryy** [comment]
typeはwireXと統合することにします

**Comment by akouryy** [comment]
結構強そうなブロックなのでwireに似てますがweightは2にしますか
junctionより低レベルっぽいdiodeが3なので同じ3にした方がいいですか

**Comment by hakatashi** [comment]
うーん難しい⋯⋯個人的には2、かなぁ⋯⋯

**Comment by akouryy** [comment]
diodeの方が低レベルというのは嘘っぽいですね
2にします
