### ISSUE TITLE
いくつかの追加算術ブロックを実装

### ISSUE THREAD

**Issue by hakatashi** [tsg-ut/mnemo#143]
いずれもテスト必須。

## const-3.png

![](https://github.com/tsg-ut/mnemo/raw/master/image/const-3.png)

入力を3にする。

## const-10.png

![](https://github.com/tsg-ut/mnemo/raw/master/image/const-10.png)

入力を10にする。

## div-10.png

![](https://github.com/tsg-ut/mnemo/raw/master/image/div-10.png)

10で割る。

## times-10.png

![](https://github.com/tsg-ut/mnemo/raw/master/image/times-10.png)

10を掛ける。

## log.png

![](https://github.com/tsg-ut/mnemo/raw/master/image/log.png)

底を左の値とする右の値の対数を下に送る。結果は0方向に丸める。

## log10.png

![](https://github.com/tsg-ut/mnemo/raw/master/image/log10.png)

底を10とする対数に変換する。結果は0方向に丸める。

## log2.png

![](https://github.com/tsg-ut/mnemo/raw/master/image/log2.png)

底を2とする対数に変換する。結果は0方向に丸める。

**Comment by kurgm** [comment]
やります
