### ISSUE TITLE
powブロックでInfinityじゃなくてNaNになる

### ISSUE THREAD

**Issue by kurgm** [tsg-ut/mnemo#156]
Infinity ** 1 とか 0 ** -1 とかが Infinity になるべきなのに NaN になる。
-Infinity ** 1 とか -0 ** -1 とかが -Infinity になるべきなのに NaN になる。

**Comment by cookie-s** [comment]
これ、parseIntのせいですね。
Math.floorにすると-Infinity方向に丸められてしまいますが、やはり0方向に丸めるべきですか？（一応仕様とも取れるtestには0方向に丸めることが書いてある）
もし0方向に丸めるとなると、http://liosk.blog103.fc2.com/blog-entry-213.html みたいに符号で条件分岐させる感じになりますね

**Comment by hakatashi** [comment]
powの出力は #128 あたりの議論で0方向に丸めることにしたはず

**Comment by cookie-s** [comment]
はい。
またもやutil.jsに関数追加してもいいですか。（0に丸めるの、以後も使うことがありそう？）

**Comment by hakatashi** [comment]
:ok_man:
