### ISSUE TITLE
.board-frameをborder-imageプロパティで簡略化

### ISSUE THREAD

**Issue by hakatashi** [tsg-ut/mnemo#160]
フレームを描画するのに9個もdivを使ってるのはヤバいのでCSS3で置き換えたい。

非対応ブラウザはスルーで。

**Comment by cookie-s** [comment]
border-image見てみましたが、今のデザインを保ちながらってのは無理じゃないですかね...(repeatとstreatchしかないので、パイプの途中にくっついてるつなぎ目とか蛇口（？）をどうしようもない)

**Comment by hakatashi** [comment]
.board-frameというのはこれのことです。
![2016-12-13 19_38_42-mousegesturel ahk](https://cloud.githubusercontent.com/assets/3126484/21137132/de00eea4-c16b-11e6-9bc9-2a2b762057ed.png)

**Comment by cookie-s** [comment]
あ、なるほど。
