### ISSUE TITLE
Math.log10(1000) !== 3 問題

### ISSUE THREAD

**Issue by hakatashi** [tsg-ut/mnemo#162]
#155 で物議を醸したMath.log問題に対処し、logブロックの仕様を修正する。

具体的な仕様として、以下を満たしている必要がある。

* log_10(99) === 2
* log_10(1000) === 3
* lag_10(1e15) === 15
* lag_10(1e15 - 1) === 14

**Comment by cookie-s** [comment]
文字化してサイズ測るのはだめになったんですか

**Comment by kurgm** [comment]
logブロックに関しては底が37以上だとつらそうですがlog10・log2ブロックならそれでいけそう

**Comment by kurgm** [comment]
```js
> (1e+20).toString(10)
'100000000000000000000'
> (1e+21).toString(10)
'1e+21'
```
あっはい

**Comment by cookie-s** [comment]
#165 してみましたが、1e15とかのtest足してないし今やってみますね...

**Comment by cookie-s** [comment]
>log_10(1e15) === 15
>log_10(1e15 - 1) === 14

のtestはpassしました。

eslintもpassさせました。

**Comment by cookie-s** [comment]
#165 fixed.
close.
