### ISSUE TITLE
divの実装がおかしい

### ISSUE THREAD

**Issue by moratorium08** [tsg-ut/mnemo#178]
-9 / 2 は-5になるべきだが、-4になっている。

これはMath.floor(a/b)で良いはずなのに、（責任の所在は僕にあるんですが）(a - a%b) / bというオレオレfloorを実装してしまったことにあり、Math.floorに置き換えれば治ります

**Comment by hakatashi** [comment]
-9 / 2 が -5 かどうかはわりと検討の余地がある気がしてる。

個人的には 9 / 2 が 4 なら -9 / 2 は -4 だろという気持ちが強い。

**Comment by moratorium08** [comment]
えーッ（なんか、余りは正の数だろという気持ちが強いです・・・（というか正の場合と負の場合でモノが違うのはなんかメリットがあるのかよくわからないです）（ただ、Cもそうらしいので、プログラミングするならそっちの常識に合わせるべきっぽいですが））
