### ISSUE TITLE
テストケースを増やす

### ISSUE THREAD

**Issue by moratorium08** [tsg-ut/mnemo#183]
テストケースが弱すぎて、条件分岐基本2,3などでの@moratorium08のようなダーティプレイが可能となってしまう（一般性がなく、テストケースのみには通るような解き方）。

なので、ランキング登録段階でバリデーション時により多くのテストケースを課して、そのようなプレイイングを排除した方がよさそう。

**Comment by hakatashi** [comment]
うーん、手元では通るのにランキングは送信できないという状況を作りたくないし、実装の手間もかかるのでやりたくない⋯⋯。MNEMOは競技プログラミングとかではなくパズルゲームなので、あまり厳密性を求めてはいない感じ。なので、嘘解法でも通れば勝ちだと思ってる。

ちゃんと厳密に解かせたいステージなら現状のシステムでテストケースをたくさん作ればいいし、「条件分岐基本2,3」はチュートリアルの一環という認識なので、そこまで厳密にする必要もないかなと。

**Comment by hakatashi** [comment]
#187 と #188 で対処することにしたので、こっちは閉じます。
