### ISSUE TITLE
ioGeneratorのテストを乱数を変えながら複数回回すようにする

### ISSUE THREAD

**Issue by cookie-s** [tsg-ut/mnemo#210]
test/unit/stages.lsでテストするとき、io-generatorがinputに重複があるテストケースを返すと、
io-specのuniqueness of inputを調べているところでコケる。

``` diff
diff --git a/test/unit/stages.ls b/test/unit/stages.ls
index 4da940a..1dd52bf 100644
--- a/test/unit/stages.ls
+++ b/test/unit/stages.ls
@@ -82,8 +82,10 @@ describe 'Stage Data' ->

   describe 'conditional01 stage' ->
     It 'generates 2x if even, 3x otherwise' ->
-      io = conditional01.io-generator @random
+      for i from 1 to 98
+        io = conditional01.io-generator @random

+      io = conditional01.io-generator @random
       expect io .to.satisfy io-spec

       expect zip io.input, io.output .to.all.satisfy ([input, output]) ->
```
とかすると、99回目の乱数を元にio-generatorがされて、
```
 1 failing

  1) Stage Data conditional01 stage generates 2x if even, 3x otherwise:

      AssertionError: expected [ 5, -10, 5, 116 ] to deeply equal [ 5, -10, 116 ]
      + expected - actual

       [
         5
         -10
      -  5
         116
       ]
```
となる。

**Comment by cookie-s** [comment]
uniquenessは保証されなきゃいけないのか、io-generatorが悪いのか。
uniquenessを保証しなきゃいけないのなら、io-specの検査は弱い気がする。

**Comment by cookie-s** [comment]
below 200であるのも、これでいいのかなぁ感

**Comment by hakatashi** [comment]
テストケースを乱数にしてるのはテストの複雑性を上げるためなので、uniquenessが保証されないようなテストを生成するioGeneratorは意味がない、つまりuniquenessは保証されるべきだと思ってる。

なので「io-specの検査は弱い気がする」というのは尤もで、本来は1回ぽっきりじゃなくてrandomの値をランダムに変えて何百回もテストするべき。

ただ、それをするとテストが落ちた時に再現性が低くてつらくなるので、テストが落ちた時に「どの乱数で落ちたのか」を同時に報告するしくみが必要。そのあたりがめんどくさいのでまだ手を付けてないんだけど、やらなきゃいけないのは確かなので、誰かに手を付けてもらいたい。

**Comment by hakatashi** [comment]
> below 200であるのも、これでいいのかなぁ感

BDD的にはこれが正しいと思う。具体的にどの数字が生成されるかまでテストに書いてしまうと、他の些細な部分が変更された時にrandomが生成する乱数も変わってテストを書き直さないといけない。しかも変更されたあとの値がその値で「正しい」のかというのはちゃんと乱数の仕様まで調べないと保証できないので意味がない。なのでこの部分で検査するべきなのは200以下という1点のみ、という理屈。

**Comment by cookie-s** [comment]
や、たかが一回200以下だったからって通していいのかなぁという話でした。

**Comment by hakatashi** [comment]
あ、なるほど

**Comment by cookie-s** [comment]
これって、普通に、上で書いた
```
for i from 1 to 98
```
の及ぶ範囲を下まで広げるだけじゃだめですか？（つまりインデントを増やす）

**Comment by hakatashi** [comment]
うーん、1回目のioGeneratorの実行に、2回目以降のioGeneratorの実行が依存するのは微妙な感じなので、できればループを回すごとにシードを初期化したい気分。

あと、それらの処理をステージごとに書くのは冗長なので、io-specみたいな感じで1箇所にまとめて欲しい。

さらに加えてoptionalだけど、テストが落ちた時に、その時のシードの値が報告されるようになっているとなおよい。
