### ISSUE TITLE
スマホでやると、ボードからブロックが削除できない

### ISSUE THREAD

**Issue by moratorium08** [tsg-ut/mnemo#214]
そもそも右クリック、実際あまり直感的ではない・・・？

**Comment by hakatashi** [comment]
いちおう、ブラウザによるけど長押しで削除できるはず。

右クリック、PCでは最適解じゃないかと思ってるけど、スマホだと微妙だよね……。そこらへんも加味してスマホ版リニューアルしたい。

**Comment by Yosshi999** [comment]
消しゴムボタン(中身はただの空白ブロック)を作ればよさそう？

**Comment by cookie-s** [comment]
#139

**Comment by Yosshi999** [comment]
そういえばcountの件も解決されてますね
ただブロック一覧に含めるよりも枠外に置きたいです
