### ISSUE TITLE
問題の移行時のクッション

### ISSUE THREAD

**Issue by moratorium08** [tsg-ut/mnemo#22]
ワンクッションあった方がいいと思います（すぐに完成した回路が消えてしまうと悲しいので）
（個人的には、ここで正解したということをサーバーに送信して、簡易的に正解数で難易度表示が出来たりしたら便利かなと思うので、余力と技術力が足りれば、ここ夜実装します・・・）

**Comment by hakatashi** [comment]
問題の構成を見直す(「チュートリアルステージ」と「その他のステージ」に分ける)のも含めてやります。
