### ISSUE TITLE
Safariでも表示が崩れる問題

### ISSUE THREAD

**Issue by moratorium08** [tsg-ut/mnemo#220]
![2017-01-03 22 02 40](https://cloud.githubusercontent.com/assets/4726469/21608537/7518ae4a-d200-11e6-8ca9-b9d59504a4a8.png)

**Comment by hakatashi** [comment]
Mac持ってないのでMac持ってる諸氏に検証・修正してほしい

**Comment by kurgm** [comment]
よく見ると「x∞」もなんか変

**Comment by kurgm** [comment]
デザインリニューアル (#298) で解決しました :)
