### ISSUE TITLE
Safariでブロック数などの表示が崩れる問題

### ISSUE THREAD

**Issue by kurgm** [tsg-ut/mnemo#221]
![2017-01-03 22 37 38](https://cloud.githubusercontent.com/assets/14951262/21609359/49538014-d205-11e6-9d88-62f6b96a00e7.png)

「x∞」の「x」と「∞」が重なっている。「x1」が消えている。流れてるデータの中身が消えている（致命傷）。

たぶん「∞」以外のグリフの字送りが0として計算されている？
`font-family`からinfinityを消すと（重なったり消えたりする問題は）治る。

Safariバージョン10.0.2 (12602.3.12.0.1)

**Comment by moratorium08** [comment]
これ、僕のスマホの方のChromeでもなるんですよねえ（なので、スマホでもやりたくてもできない）

**Comment by hakatashi** [comment]
激やば問題っぽいのでmac/iosではwebfont消すとかして応急処置したい

**Comment by kurgm** [comment]
とりあえず、 `font-family: infinity, 'Exo 2', sans-serif;` を `font-family: 'Exo 2', infinity, sans-serif;` にしてやると正常になります
