### ISSUE TITLE
modal 04の加算のデータの流れがおかしい

### ISSUE THREAD

**Issue by cookie-s** [tsg-ut/mnemo#226]
mnemoを開いて、四則演算基本6をステージセレクトすると、モーダルが出るが、その中の加算動画のデータの流れがおかしい。

ほんとは動画を上げたいんだけどスクショで許して。
![default](https://cloud.githubusercontent.com/assets/1732074/21758608/c1774920-d680-11e6-83fc-ec683258ce37.PNG)
left + up -> rightという流れになってる。

![2](https://cloud.githubusercontent.com/assets/1732074/21758609/c17846e0-d680-11e6-9e7d-8ce15d1fd905.PNG)
githubでmodals/04/add.svgをプレビューしたときは、そんなことなく、正しく left + right -> bottomとなってるのに。

**Comment by hakatashi** [comment]
(imgとしてではなく)SVGをHTMLに直接埋め込んでいるので、クラス名が他のSVGと衝突してこういうことになるのです⋯⋯。なんか前も同じようなことがあって直してもらったような。

根本的に解決したいけどどうすればよいやらという感じ。

**Comment by cookie-s** [comment]
new Boardで1x1のボードをそこにつくって、new Blockを配置してDataをinputできたら最高だけどなぁとか思った

**Comment by hakatashi** [comment]
処理の一貫性的にはよさそうだけどお相当めんどくさそう⋯⋯。

ちなみにSVGをimgとして読み込むのは、外部リソースが読めないという制限で諦めた。
