### ISSUE TITLE
Reactをアップデートできない件を修正

### ISSUE THREAD

**Issue by hakatashi** [tsg-ut/mnemo#252]
Reactを15.4.2から15.5系にアップデートすると、なぜかmochify:phantomのテストが、テストケースがすべて通るのにもかかわらす exit 1 する。謎。

Reactをアップデートできないのはつらいので、調査して修正する。

参考: #251

**Comment by kurgm** [comment]
react-domがconsole.errorで「Warning: Shallow renderer has been moved to react-test-renderer/shallow. Update references to remove this warning.」と表示してるのが元凶（→phantomicが終了時にphantom.exit(1)してmochifyがコケる）で、まあconsole.errorがあったらexit(1)するのは妥当な気がするので、referencesをupdateしてこれを消すのが解決法っぽいです。（が、どこにreferencesがあるのかよく分からないので探している）
