### ISSUE TITLE
ブロックの追加

### ISSUE THREAD

**Issue by satos---jp** [tsg-ut/mnemo#28]
1.  -1ブロック (無いと階乗とかを-2+1みたいにやる必要があるので)
2.  constブロック (定常的にxを出すの)(無いと毎回わざわざ作る必要がある)
3. mod(剰余)ブロック (回路が本質でないとこで複雑化しない)

があるとよいかとおもいます(別になくても解けるが不本意な面倒くささは遊ぶ楽しさを低下させる？)
ほかにも、いままで解いた問題をひとつのパーツにしたやつがあるとよいです？(例えば階乗の値を返す階乗ブロックとか)

**Comment by hakatashi** [comment]
1. よさそう
2. constブロックは考えたが現状の機構がデータがやってこないと動かないようになってるので実装がめんどくさそう……
3. よさそう

> いままで解いた問題をひとつのパーツにしたやつ

面白そうだけど、正直あまりパズル的ではない気がする

**Comment by satos---jp** [comment]
÷2,÷3, pow, const(どんな入力に対しても0,1,2を返す), とかもあるとよいかと。

**Comment by hakatashi** [comment]
必要そうな画像追加しました

**Comment by hakatashi** [comment]
done
