### ISSUE TITLE
Fork me on GitHub リボンが邪魔

### ISSUE THREAD

**Issue by akouryy** [tsg-ut/mnemo#315]
画面を(ブラウザ自体の機能で)縮小したときにGitHub Ribbonとブロック選択パネルが重なって、ブロックを選択しづらくなります。
![fork-ribbon-315](https://user-images.githubusercontent.com/2476461/27758562-40ec79e2-5e52-11e7-89d0-120f919eefb9.png) Google Chrome ver 59.0.3071.115

解決策としては
- パネルかリボンのサイズを調整する
- タイトル画面以外ではリボンを表示しないようにする

の2つが考えられますが、私は後者でいいと思います。

**Comment by hakatashi** [comment]
リボン非表示の方針でよさそう

**Comment by akouryy** [comment]
がんばるぞい

**Comment by akouryy** [comment]
テスト書かなくていいですか？

**Comment by hakatashi** [comment]
書かなくてよいです
