### ISSUE TITLE
Browserify + Mochify + Mocha + Istanbul => Webpack + Karma + Mocha + Istanbul

### ISSUE THREAD

**Issue by hakatashi** [tsg-ut/mnemo#316]
Inherits #98.

# 解決できること

* CSSをJSにバンドルできるようになる
* PhantomJSつらいのでElectronに移行できる
* mochify-istanbulのソースマップがおかしいせいでカバレッジの行数がずれる問題が解決する (はず)

**Comment by hakatashi** [comment]
やるよー

**Comment by cookie-s** [comment]
これ、もう終わった？（よくわからない）

**Comment by hakatashi** [comment]
あ、おわった
