### ISSUE TITLE
データが無くなってもstopボタンがexecuteボタンにならない

### ISSUE THREAD

**Issue by kurgm** [tsg-ut/mnemo#317]
再現手順：

1. 「練習」以外のステージを開く
2. 何も置かずに（or 適当に入り口にwireIを一個だけ置いたりして）executeボタンを押す
3. 実行終了後、下のstopボタン（⏸）が表示されたまま、executeボタン（▶️）が表示されない

練習ステージでは再現しないという謎のバグです

**Comment by hakatashi** [comment]
謎すぎる

**Comment by cookie-s** [comment]
閉じちゃうよ

**Comment by cookie-s** [comment]
治ってなかった。配列inputのときにだめっぽい。
僕それについては知らない。

ex. 配列基本1, 中央値

**Comment by kurgm** [comment]
枝刈り #326 の前の a105077f3f90c713c35633e261e2e071667b642d に戻すとうまくいくので #326 が問題っぽいです

**Comment by cookie-s** [comment]
なるほど残念
