### ISSUE TITLE
ブロックの重みを見たい

### ISSUE THREAD

**Issue by cookie-s** [tsg-ut/mnemo#336]
ブロックの重みがスコアに影響してくるわけだが、どのブロックがどう影響しているのかわかりたい。
どこをなくすといいのかなーっていう指標にしたい。

右のpanelでカーソルを合わせるとポップアップで分かるとか、
クリア後にそれぞれのブロック上に重みが表示されるとか？

**Comment by hakatashi** [comment]
#78 で解決したい
