### ISSUE TITLE
旧バージョンのブラウザへの対応

### ISSUE THREAD

**Issue by moratorium08** [tsg-ut/mnemo#46]
今日の様子を見ていると、人々の持つスマホはバージョンが必ずしも新しくないので、うまく動かないことが５０％くらいの確率だったので、やや古めのiPhone safariとかで動いた方が回転がよくなりそう

**Comment by hakatashi** [comment]
今日の夕方ごろスマホ版のMNEMOにもAutoprefixerを入れました。 5b689352a6c805c7060cb59039a65e28bc73db2b Safariならだいたい動くはず。flexすら動かない旧石器時代のブラウザは(*ﾟДﾟ)ノ ﾟ ﾎﾟｨ

**Comment by kurgm** [comment]
CSSというよりJSの問題の気がしています…（試しに古いiPhoneを引っ張り出してきたらObject.assignはundefinedだと怒られました）

**Comment by hakatashi** [comment]
あっ……修正します

**Comment by hakatashi** [comment]
0280cf40c928914c36bf8ad51ac919441c1d2a39 で直ったはず

**Comment by kurgm** [comment]
- `sp` ブランチにも導入が必要です
- 以下がサポートされればそれなりに動きます
    - Object.assign
    - Array.from
    - Array::includes
    - Promise

**Comment by hakatashi** [comment]
core-js丸ごと入れるか……

**Comment by hakatashi** [comment]
入れた d11a65c3bf8181ccc93beccaffe78d53b3bf573f
