### ISSUE TITLE
セーブ機能

### ISSUE THREAD

**Issue by hakatashi** [tsg-ut/mnemo#55]
Boardの状態をセーブデータとしてlocalStorageあたりに保存できるようにし、Stageに関連づけてゲーム画面からセーブ/ロードできるようにする。

ついでにメニューのステージセレクト画面でどのステージをクリアしたかが一目でわかるようになっているとよい。

**Comment by cookie-s** [comment]
盤面下のcontrolの所にボタンが二つ増えて、そこからセーブ/ロードができるという認識であってますか。
セーブスロットは1つで問題無いですよね

**Comment by hakatashi** [comment]
スロット無限にしたいなぁ。

> 盤面下のcontrolの所にボタンが二つ増えて、そこからセーブ/ロードができる

うーん、同じ場所にむやみにボタン増やしたくないが……でもそこしか置く場所ないか……ただボタンは「セーブ/ロード」ボタンが一つあるだけでよいと思います。

**Comment by cookie-s** [comment]
デザインというのはボタンその他のデザインのこと？URLのデザインのこと？
絵描きはできないです

**Comment by hakatashi** [comment]
ボタンとかのUI/UX設計のデザイン。

**Comment by hakatashi** [comment]
![2](https://cloud.githubusercontent.com/assets/3126484/18897363/a9c748ec-8564-11e6-9253-138959bd864d.png)

**Comment by kurgm** [comment]
Resolved by #296 :)
