### ISSUE TITLE
リリース用にCSSとJSをminifyする

### ISSUE THREAD

**Issue by hakatashi** [tsg-ut/mnemo#68]
CSSはcssnanoかCSSWring, JSはuglifyfyを使うといいと思う。

ビルドが重くなるので通常のビルドコマンドとは分けておきたい。

**Comment by cookie-s** [comment]
$ cat index.css | wc
   1534    4358   42584
$ ./node_modules/.bin/cssnano index.css | wc
      1    1036   32064
$ ./node_modules/.bin/csswring index.css | wc                                                                                                      
      0    1053   32595f
cssnanoのほうが500bytesほど小さくなった。

cssnanoのほうが機能が豊富で、ググると[困ったことがあった人もいた](http://qiita.com/nsyan/items/3f04f0e962df42cf25f7)らしいけど、
困るまではこれでもいいのかなと思ったんですがどうでしょう。

**Comment by hakatashi** [comment]
よさそう。

**Comment by cookie-s** [comment]
done.
