### ISSUE TITLE
インターネット接続がない状態で機能テストを実行するとタイムアウトする

### ISSUE THREAD

**Issue by hakatashi** [tsg-ut/mnemo#72]
subtlepattern や Google Analytics などの外部リソースを読みに行ってるためだと思われる。

そもそもテストのたびに外部リソースを読みに行くのはよろしくないので、これらをなくすか、もしくは適切にNightmare側で打ち切って処理を続行できるようにする。

**Comment by cookie-s** [comment]
analyticsはとりあえず、
``` javascript
if (process.env.NODE_ENV === 'production' && process.env.MOCHIFY !== 'true') {
```
が加えられて治ってますよね。

DEBUG=*としながらnpm run functionalをすると、少なくともはじめに引っかかってるのは、
https://fonts.gstatic.com/s/exo2/v3/GJUUsjMsQG_gk-UGzcMXofesZW2xOQ-xsNqO47m55DA.woff2
っぽいです。

**Comment by cookie-s** [comment]
lessで環境変数にアクセスする方法はないのかなぁ。

95.7KBのwoffファイル、ダウンロードしておいておきますか。
