### ISSUE TITLE
小画面対応

### ISSUE THREAD

**Issue by cookie-s** [tsg-ut/mnemo#84]
Chromium, Version 53.0.2785.116 (64-bit)
Display: 1280x720px

I/O表が大きすぎる？

![captureimage](https://cloud.githubusercontent.com/assets/1732074/18811987/0d937494-82ff-11e6-9a17-25cc63c5e12b.png)

**Comment by cookie-s** [comment]
画面が小さすぎるということですか？
推奨環境がある？

**Comment by hakatashi** [comment]
> 画面が小さすぎるということですか？

その通り……だけどこれくらいの解像度だったらまともに遊べるようにしたいとは思っている。スマホ対応(#40)も含めて……。
