### ISSUE TITLE
JSがうまくminifyできてないっぽい

### ISSUE THREAD

**Issue by hakatashi** [tsg-ut/mnemo#89]
コメントとかインデントとか残ってる。要調査。

``` js
$ head index.min.js -n 2500 | tail
var create         = require('./_object-create')
  , descriptor     = require('./_property-desc')
  , setToStringTag = require('./_set-to-string-tag')
  , IteratorPrototype = {};

// 25.1.2.1.1 %IteratorPrototype%[@@iterator]()
require('./_hide')(IteratorPrototype, require('./_wks')('iterator'), function(){ return this; });

module.exports = function(Constructor, NAME, next){
  Constructor.prototype = create(IteratorPrototype, {next: descriptor(1, next)});
```

**Comment by cookie-s** [comment]
これどのindex.min.cssですか？
現時点のhttp://sig.tsg.ne.jp/mnemo/index.min.css はわりとよさそうなんですが

**Comment by cookie-s** [comment]
あ、jsか。ごめんなさい

**Comment by hakatashi** [comment]
CSSじゃなくてJSっす

**Comment by cookie-s** [comment]
自分たちで書いてないmoduleのjsと、あとstages.jsonですね

**Comment by kurgm** [comment]
https://github.com/hughsk/uglifyify のREADMEを見ると

> When using uglifyify you should generally **also** use Uglify, to achieve the smallest output.

って書いてあるのでそれですかね

**Comment by hakatashi** [comment]
mjd...

**Comment by hakatashi** [comment]
[minifyify](https://github.com/ben-ng/minifyify)試してみてほしい

**Comment by cookie-s** [comment]
> WARNING: Unmaintained!
> I have stopped writing Javascript full-time, and therefore do not use Minifyify anymore.

とかありますけど...

**Comment by hakatashi** [comment]
えー⋯⋯。

そのWARNINGついたの9日前っぽいし、言うてだいたいどのライブラリも実質unmaintainedみたいなもんだし(暴論)、試す価値はありそう

**Comment by cookie-s** [comment]
閉じます #209
