### ISSUE TITLE
Webpack化

### ISSUE THREAD

**Issue by hakatashi** [tsg-ut/mnemo#98]
現状BrowserifyでJSをビルドしているのをWebpackに置き換えたい。
# 意図
- とりあえずWebpackのほうが後発だし使っときたい
- ゲーム上で細かい画像ファイルをたくさん読み込んでるのがボトルネックになってるので、Webpackで解決したい
  - というかゆくゆくはSVG化したい
# 問題(になりそうな)点
- 現状大量にぶっこんでる Browserify Transform と同じ機能をWebpackで提供できるか?
- Mochifyと衝突しないか?
- PostCSS/LESSと共存できるか?
  - LESS廃止(#93)と合わせて検討したい

**Comment by cookie-s** [comment]
これも終わってそう？

**Comment by hakatashi** [comment]
終わってるー
